Switch to c11 and remove old javascriptcore check
compiling agains webkit raises warnings, as webkit is c11 based. If
Webkit needs it, we can as well switch to c11.

/usr/local/include/webkitgtk-4.0/jsc/JSCException.h:43:28: warning: redefinition of typedef
      'JSCContext' is a C11 feature [-Wtypedef-redefinition]
typedef struct _JSCContext JSCContext;
                           ^
/usr/local/include/webkitgtk-4.0/jsc/JSCClass.h:40:28: note: previous definition is here
typedef struct _JSCContext JSCContext;
                           ^

This commit also removes a check for older Webkit GTK versions, which
bundle JavaScriptCore. These Webkit Versions are not supported anymore
for quite some time.